---
  :server:        "127.0.0.1"
  :port:          6000
  :initial_state: "capture_flag"
  :refresh:       0.1
  :strategy:      false
  :debug:         false
  :abort_on_int:  true
# This line makes ctrl-C dump a PDF map of the world:
  :pdf_file:      map.pdf
# This line makes ctrl-C update the running state:
  # :state:         wait,smart
